### ISSUE TITLE
Document various "aux" functions and additional helpers

### ISSUE THREAD

**Issue by sbrth** [imbrn/v8n#101]
The code is littered with helpers that some might not understand. To enable contributions these functions need to be described in a comment. It can be kept brief but should say what the function does and what it returns. Especially those functions returning functions need to receive this treatment. This is an important step in cleaning the code.

**Comment by imbrn** [comment]
I'll change some variable and functions names soon to improve code readability. I'm also working on a docs section explaining better how the algorithm which connects rules and modifiers together works.

**Comment by sebastianbarfurth** [comment]
Once these are slightly refactored and correctly documented I will tackle #48 again.
