### ISSUE TITLE
Possibility to include extra information along with validations

### ISSUE THREAD

**Issue by imbrn** [imbrn/v8n#108]
**What is this proposal about?**

An issue was filled asking some kind of i18n support from `v8n`. Take a look at #107 

Actually, this kind of feature is more related to the presentational layer of an application. And it's not a _v8n_'s role to provide a messaging system, but to provide a validation solution for as many use cases as possible.

But in fact, we need to provide some kind of "help" to developers for mapping validations into messages. But we should keep things simple, fluent and in accordance with all of the main goals of this library.

I was thinking about that, and I ended up with the fact that we should provide a way to identify validations better, like with an ID or something like that. But I realized that we shouldn't keep things strictly tied to ID's or any other kind of data, but instead, we could provide an abstract mechanism for the developer to define what he/she wants to tie with his/her validation.

So my proposal is to provide a feature where the developer can provide more information to attach with the validation process.

---

_The following solutions have crossed my mind:_

- **Passing extra data along with the `v8n` function:**

```javascript
v8n({ id: "name" }).string().not.empty().check("");
// ValidationError{ id: "name", ... }
```

At a first glance, this solution looks nice. But there are situations where it makes no sense, as when we branch a validation from another validation. Look:

```javascript
const numbers = v8n({ id: "numbers" }).number();
const positive = numbers.positive();
const negative = numbers.negative();
```
- **Passing extra data with the validation functions:**

```javascript
const name = v8n().string().not.empty();
name.check("", { id: "firstName" });
name.check("", { id: "lastName" });
```

This syntax looks a little weird to me, and it also requires some more work to be done to make it work with all the validation methods.

- **Higher-order validation**

_This is my favorite solution, as it is very functional, and it does not conflict with any of the current API. But indeed it's more difficult to implement and maybe should not look very familiar for everyone._

```javascript
const name = v8n().string().not.empty();

withExtra({ id: "firstName" })(name).check("");
// ValidationError{ extras: { id: "firstName" }, ... }
```

All these solutions have advantages and disadvantages, but we need to discuss more them so that we can understand them better to avoid future problems. We can also end up with other better solutions after all.

**Comment by sebastianbarfurth** [comment]
The last approach looks awful. Function chaining with function returns is not a desirable pattern, it looks confusing. Also withExtra is another top-level function, which seems odd. Why is not part of v8n?

I don't get the notion of this issue. It's the developers job to keep track of validations and I velieve we provide enough data as is to do this effectively. I don't see the use-case here?

**Comment by imbrn** [comment]
You're absolutely right @sebastianbarfurth. Actually, this proposal is just something that crossed my mind and I wanted to share it so we could talk about.

I agree with you that it's a developer responsibility to take care of the validation output, but I was thinking we could maybe "help" with mappings in some abstract way. But that's just something that came to my mind. I have no clear understanding about its usage though.

And about the `withExtra` approach, man I think it's beautiful, but I came from a functional background, and I know that this kind of syntax looks awful for almost everyone.

Anyway, this is just something for us to discuss. I don't know if this kind of feature can be worth. Maybe we can provide something like that in a separated project. I don't know. But thank you for your help, man.

**Comment by sebastianbarfurth** [comment]
This syntax looks bad for most devs:

```js
someFunction(someArg)(someOtherArg)
```

I would agree it's not a desirable syntax. You don't actually know from that piece of code what function you're executing. It lacks clarity. It's not so much code style as it is understandability (though I also dislike the style, but that's subjective). I don't have a particularly great solution though. We should probably find specific application for this, so that maybe we could model it around it.
