### ISSUE TITLE
Bug with `integer` rule

### ISSUE THREAD

**Issue by imbrn** [imbrn/v8n#117]
The `integer` rule has a bug when it needs to use its polyfilled version. Look:

https://github.com/imbrn/v8n/blob/10216d26527459c9f458efd940929f02f4c92385/src/v8n.js#L150

This code is going to throw an exception when `Number.isInteger` is not present, instead of fallback to the polyfill test.

It should first detect for the `Number.isInteger` presence and fallback to the polyfill before calling it, like this:

```javascript
(Number.isInteger || testIntegerPolyfill)(value)
```
---

> NOTE: This is a bug fix that has to be solved as soon as possible. And it must go in a patch version. It needs to be fixed upon the `stable` branch instead of `master`.

**Comment by sebastianbarfurth** [comment]
No need for the weird syntax. We can define the Polyfill as MDN describes. Then just call the Polyfill.
