### ISSUE TITLE
Publish dist folder to git

### ISSUE THREAD

**Issue by barfurth** [imbrn/v8n#180]
Most large projects that build from a `src` folder publish their `dist/` folder to git. We don't do this and I believe this gives us a few issues. People who don't want to build themselves or use *npm* can't download an ES5 compatible version from git. We also don't have insight for everyone which builds we actually provide. I think it would be good to publish the `dist` folder to the repo and not just to *npm*.

Examples:

- [vuejs/vue](https://github.com/vuejs/vue)
- [axios/axios](https://github.com/axios/axios)
- [moment/moment](https://github.com/moment/moment)
- [twbs/bootstrap](https://github.com/twbs/bootstrap)

As a side note: A lot of projects will publish their main file (usually UMD build) as `index.js` or `{packagename}.js` at the project root. That seems like a good idea to me as well, but not really necessary. A good example here is [moment/moment](https://github.com/moment/moment). Their project is very similar to v8n, particularly in how their API works (entry function) and their non-CJS codebase.

Of course publishing `dist` is debatable. Some do some don't. If we don't we definitely need to list our builds on GitHub and the docs.

**Comment by imbrn** [comment]
I totally agree with you that we need to publish the `dist` folder on Github, too. Actually, I believe we should both publish it and also document which builds we provide.

About the `index.js` file in the project root, I like the idea of having just the `dist` folder with all the builds. But we can discuss that as well.

**Comment by brfrth** [comment]
@imbrn done in #177
