### ISSUE TITLE
Can we have a full example for async rules?

### ISSUE THREAD

**Issue by joelephroni** [imbrn/v8n#182]
My rule returns {controlName: {}} instead of {controlName: "errorMessage"}. I have been pounding my head against this all day, and nothing seems to produce the right errors object. Help? What should the custom method return and what should the rule return in the 'then' and 'catch' clauses?

**Comment by brfrth** [comment]
Hi @joelephroni - sorry about the long delay. If you're still wondering about this I would like to take a look. It would be good if you could provide some sort of reproduction code.

**Comment by barfurth** [comment]
Closing this for now. Please open a new ticket if you still have a question.
