### ISSUE TITLE
Logo has bad contrast on GitHub in dark mode

### ISSUE THREAD

**Issue by barfurth** [imbrn/v8n#220]
The logo displayed at the top of the `readme` has bad contrast when dark mode is active on GitHub. Perhapt a slightly lighter grey could be used for the font. Here is a screenshot of this issue:

<img width="921" alt="Screenshot 2022-02-17 at 17 10 51" src="https://user-images.githubusercontent.com/6641565/154522587-28c02dd6-0ec1-46da-9d49-62c17da9db83.png">

It may be more welcoming for new consumers if the logo was a little better to read. Obviously a different shade of gray would not work on all backgrounds. For a more universal solution it might be an interesting thought to have the text colored green like the logo or some other, less common color.

I'm no designer, I just thought this may be worth keeping track of.

**Comment by Seung-hwan285** [comment]
Hello barfurth 
Would it be okay to design some logos and upload them?

**Comment by barfurth** [comment]
Hey @Seung-hwan285! I'm gonna pass this question to @imbrn who can give you a definitive answer.

**Comment by imbrn** [comment]
Hello @Seung-hwan285 and @barfurth.

@Seung-hwan285 thank you very much for your interest in contributing. You're really welcome to do that.
You can open a pull request replacing the current logo with your suggestion.

**Comment by Seung-hwan285** [comment]
Hello imbrn Thank you so much.

**Comment by barfurth** [comment]
Closed via #226 - thank you @Seung-hwan285
