### ISSUE TITLE
Security concern

### ISSUE THREAD

**Issue by JamieSlome** [imbrn/v8n#231]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@vovikhangcdv) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by imbrn** [comment]
Thank you @JamieSlome for the report. The SECURITY. md file is created with our contact email as recommended by github.

**Comment by JamieSlome** [comment]
@imbrn - appreciate your diligence 👍 

We will get an e-mail sent over to you shortly. Otherwise, you can view the report directly here in the meantime:
https://huntr.dev/bounties/2d92f644-593b-43b4-bfd1-c8042ac60609/

It is currently private and only accessible to you :) If you do not want to sign-up, the e-mail will provide you access to the report without having to sign in.
