### ISSUE TITLE
Support TypeScript

### ISSUE THREAD

**Issue by isergey** [imbrn/v8n#28]
Thank you!

**Comment by sebastianbarfurth** [comment]
What type of support would you want exactly? This will run perfectly fine inside TypeScript, at least in theory.

**Comment by Azael05x** [comment]
He probably meant to provide typings (@types/v8n)

**Comment by isergey** [comment]
Azael05x was write. Needs @types/v8n for compile time type checking.
https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

**Comment by sebastianbarfurth** [comment]
[I've submitted declarations for publishing.](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/27449)

I will update with the status here!

**Comment by imbrn** [comment]
Thank you so much @sebastianbarfurth. Very great job!

**Comment by sebastianbarfurth** [comment]
@lazarljubenovic According to the docs the @types approach is favored for non TypeScript applications, so I'm trying to go with standards here. I do see your point, I believe rewriting to TypeScript for the core is useful anyway. When that happens the types can move into the project.

For switching to TypeScript @imbrn would need to agree. It's a fairly simple switch, if we wanna do it I can probably do it today or tomorrow.

**Comment by sebastianbarfurth** [comment]
I actually feel like converting to TypeScript sooner rather than later would be a good thing. Just as an aside.

**Comment by imbrn** [comment]
Go ahead and do that! This is the last thing we need to do before releasing version 1.1. 🎉🎉

**Comment by sebastianbarfurth** [comment]
I'm nearly done, but I can't find a way to make type definitions for a Proxy based approach, since the names of functions aren't known.

**Comment by imbrn** [comment]
Maybe we should keep this feature out of the next version, and then we can think about it better.

**Comment by sebastianbarfurth** [comment]
@imbrn Yeah, I wanna do docs first and I will go ahead with this for 1.2.0.

**Comment by imbrn** [comment]
@sebastianbarfurth This library has a lot of dynamic behavior, and I think this is great. So, we really need to talk about how we can make this work for TypeScript. Maybe it needs some code refactoring to make it a little less dynamic, but this is something we quite need to discuss before though.

**Comment by sebastianbarfurth** [comment]
Removing this from 1.2.0 since this requires some additional refactoring before-hand.

**Comment by Raiondesu** [comment]
Awesome library!\
In order to properly type it, it needs to create a separate context for custom rules (upon calling the `extend` function), instead of a global variable, as it is now.

Everything else is perfectly typable.

**Comment by BottlecapDave** [comment]
Is there any update on this? I'd love to use it, but lack of typings is a bit of a deal breaker for work related projects

**Comment by trevorr** [comment]
@BottlecapDave I felt the same way regarding this being the best library I could find for fluent validation, but I didn't see a way to easily address this Typescript issue and (perhaps more importantly) the lack of human-readable error messages. Therefore, I created a new one: https://github.com/trevorr/tsfv. Maybe it will meet your needs.

**Comment by iampervaze** [comment]
Awesome lib, but not been able to use it with Angular 8. Looking forward to the typescript version. Thank you!

**Comment by lazarljubenovic** [comment]
You can use it with any framework, you just won't get types.

**Comment by iampervaze** [comment]
@lazarljubenovic could you please mention the import instruction and usage.
I have tried.

import 'v8n'

const rule = v8n().number();
const result = rule.test(22);

I am possibly doing it wrong.

**Comment by GustavTaxen** [comment]
Has there been any progress on this lately?

If Typescript support isn't coming soon for v8n, I'm afraid that we'll have no choice but to switch to a different validation toolkit.

**Comment by brfrth** [comment]
@GustavTaxen and the rest: Just created #178.

**Comment by JoelDesante** [comment]
Hi, just so you all are aware. I've forked the repository and published a version of it (with very basic typings) to npm under the name v8n.ts
https://www.npmjs.com/package/v8n.ts

My intentions are for this to be a temporary package that should be deprecated once this issue is resolved.
