### ISSUE TITLE
Add support for truthy / falsey / empty. And about the `.equal` & `.exact`

### ISSUE THREAD

**Issue by olstenlarck** [imbrn/v8n#35]
Heya! :tada: Great work and code!

Would mind adding support for this rules? ~~Where the `.empty` should work for any passed value - empty array, empty string, empty object (Object.keys(val).length?) and etc.~~

edit: oh there's `.empty` already.

As about the `.equal` and `.exact`. What about renaming them? There are few scenarions.

1/ Since even Nodejs is moving to "strict by default" for the `assert` core module, why not make `.equal` strict by default and add `looseEqual` rule?

2/ Or adding one more alias for the `.exact` - `.strictEqual`?

**Comment by sebastianbarfurth** [comment]
I feel like exact is a sound name, as a consequence equal seems like the best choice for loose checking.
