### ISSUE TITLE
Better sharable extending

### ISSUE THREAD

**Issue by olstenlarck** [imbrn/v8n#37]
Currently you can use `v8n.extend` but it does not return anything, i think a lot more better would be to return and then pass it where it is needed.

For example

customRules.js
```js
const v8n = require('v8n')

module.exports = v8n.extend({
  one: (expected) => (actual) => actual === 1
})
```

so later we can pass it for example to the `v8n()` or to new `v8n().use()`?

```js
const v8n = require('v8n')
const customRules = require('./customRules')

v8n(customRules)
  .one()
  .test(123) // => false
```

**Comment by sebastianbarfurth** [comment]
To be fair, there is no advantage to this as of now. ``v8n.extend()`` only puts the function into an array, so it doesn't actually do any processing worth returning. A ``use()`` would basically be the same but with an extra step, at least as far as I can see.

**Comment by olstenlarck** [comment]
Yes. But i definitely don't like to use `import/require` the way it is suggested. And i'm not the only one that does not like such APIs.

```js
const v8n = require('v8n')

require('./customRules')

v8n()
  .one()
  .test(123) // => false
```

Feels like a magic. No matter what it does. It's always better to be explicit, it's more visible and readable.

**Comment by sebastianbarfurth** [comment]
I agree, being explicit is better here, but you can be more explicit at this time. Rules are just functions, so this should work.

```javascript
// myCustomRule.js
export default function(expected) {
  return value => value === expected;
}
```

```javascript
// main.js
import v8n from "v8n";
import myCustomRule from "./myCustomRule";

v8n.extend({
  myCustomRule
});
```

This is my understanding anyways.

**Comment by imbrn** [comment]
You can also export multiple rules all together:

```javascript
// myCustomRules.js
export default {
  ruleOne: () => value => value === "something",
  ruleTwo: () => value => value === "another thing"
};
```

```javascript
// myApp.ja
import myCustomRules from "./myCustomRules";

v8n.extend(myCustomRules);
```
