### ISSUE TITLE
Add a CONTRIBUTING file

### ISSUE THREAD

**Issue by imbrn** [imbrn/v8n#38]
This file should communicate how people can contribute. Things like how to clone the repo, install and get the project running. And other useful information.

It can be put inside a `.github` folder.

**Comment by olstenlarck** [comment]
You might be interested in https://github.com/tunnckoCore/contributing :)

I'm always open to updates. Probably would remove the "Pro tips" section, so it may sound better for more projects. What i usually do is to add [small `CONTRIBUTING.md` like this one](https://github.com/tunnckoCore/gitcommit/blob/master/CONTRIBUTING.md) that links to the bigger one with more info for newcomers and for advanced users.

Also feel free to copy paste it. ;]

**Comment by sebastianbarfurth** [comment]
I've created a pull request with a concise CONTRIBUTING file.
