### ISSUE TITLE
ValidationException should extend Error

### ISSUE THREAD

**Issue by sebastianbarfurth** [imbrn/v8n#41]
Since ``ValidationException`` is a custom Error, it should extend JavaScripts base ``Error``. This is for consistency and handling purposes and will make the exception more rich.

There is a description on how to extend the base ``Error`` on the [MDN info page for it](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Error). This won't cause any API changes and no code changes outside the ``ValidationException`` function.

Most notably this would give the stack trace on most platforms: [Medium.com article](https://medium.com/@xjamundx/custom-javascript-errors-in-es6-aa891b173f87)

**Comment by imbrn** [comment]
I think we should do that? Can you make a PR for that?
