### ISSUE TITLE
Introduce pulling to a development branch instead of master

### ISSUE THREAD

**Issue by sebastianbarfurth** [imbrn/v8n#42]
For proper versioning pull requests should not be toward master. I believe master should represent the latest released version whereas all changes for the next version should be on another branch called ``dev``, ``develop`` or something like that. That branch could of course be default on GitHub to keep current code visible.

**Comment by imbrn** [comment]
That sounds good to me.

**Comment by imbrn** [comment]
But for now, I think we should keep it as it is. We'll still use branches for new features, but we'll keep the master branch to reflect the last modifications.
