### ISSUE TITLE
Cannot mimify by create_react_app

### ISSUE THREAD

**Issue by spot-developers** [imbrn/v8n#44]
Reports error: 

Failed to minify the code from this file: 

 	./node_modules/v8n/dist/v8n.esm.js:61

**Comment by imbrn** [comment]
Sorry about that.

This error is happening because of a misconfiguration in the build process that should transpile `esm` modules from es6 to es5.

We're going to fix this problem as soon as possible. But until then you can use the UMD version of the library:

```import v8n from "v8n/dist/v8n.umd";```
