### ISSUE TITLE
Is there any way to use this library on an env where Proxy is not available?

### ISSUE THREAD

**Issue by danechitoaie** [imbrn/v8n#45]

**Comment by imbrn** [comment]
Thank you @danechitoaie for your feedback.

At the moment, I chose not to polyfill `Proxy` because all major browsers already have support for that. But we should have some documentation explaining better how to polyfill that anyway.

But for now, you can go to this link (https://github.com/GoogleChrome/proxy-polyfill). It'll show you how you can polyfill `Proxy` in your application.

Please let me know if you have any questions.

**Comment by danechitoaie** [comment]
I want to use this on SFCC (former Demandware) and they run JS in Rhino which kind of supports an ancient version of JS. I'll try with the polyfill to see if it works.

Thanks.

**Comment by iangilman** [comment]
I guess it depends upon how you define major browsers. IE 11 doesn't support Proxy:

https://caniuse.com/#search=proxy

… and its browser share of 2.66% is significantly greater than any version of Edge, and right up there with Firefox and Safari:

https://caniuse.com/#search=proxy

… so I'd call IE 11 a major browser, unless Chrome is the only one that makes the cut.

**Comment by bassarisse** [comment]
Hi there!

We love v8n in the company I work for, but here, supporting older environments is a requirement, unfortunately. I tested the Google polyfill but got no success with it, so I managed to make the lib work without Proxies,  with a relatively small modification,.

Here's the commit:
https://github.com/bassarisse/v8n/commit/ff123c538f500a2e1dc6599816d0d3e333764960

Do you guys think it would be a good PR? Is this something you'd like to support?

PS: I forced the tests to run without Proxy, and all of them passed. I guess we'd just have to figure out a way to run the same conditions, with and without Proxy (sorry, I'm not well versed in this area).

**Comment by iangilman** [comment]
Sounds great to me! I too have a website that needs to support IE11.

**Comment by SnirShechter** [comment]
Any progress on this?

**Comment by NoemiRozpara** [comment]
Hi! I found out this is still an issue, so picked @bassarisse 's commit into the most recent version of the library and opened a PR. This is not a breaking change and a true life-savior, so I'd be more than happy to see it merged. 

Unfortunately proxy in this case can't be polyfilled - was getting an error `can't get property "empty" on null or undefined` in the following use case: 
```
const { bindValidation, getFieldError } = useFormValidation({
    validations: {
      email: v8n().not.empty()
    },
    onSubmit: fields => {
      if (onDone) onDone(fields.email);
    }
  });
```
@bassarisse 's solution was tested in IE11 / Win 10. https://github.com/imbrn/v8n/pull/171

**Comment by brfrth** [comment]
Thanks @NoemiRozpara for your pull request. It looks like it's working fine.

I'm just not quite happy with the code yet, but I think the idea is good. It adds more of a "works out of the box" feel if you never need to run an external polyfill.

**Comment by brfrth** [comment]
The PR we had for this has been closed. I might be able to take a look at this at some point. If not, @ev-akarel might be able to submit a PR that works.

**Comment by ev-akarel** [comment]
@brfrth I'll try and get to it this week. It'd be nice to not need the local fork I have.

**Comment by ev-akarel** [comment]
@brfrth Any chance you could review #184 ?

**Comment by brfrth** [comment]
@ev-akarel Sorry, I reviewed it. It looks fine :)
