### ISSUE TITLE
Add object schema rule

### ISSUE THREAD

**Issue by imbrn** [imbrn/v8n#50]
Add a rule for validating object schema values.

**Comment by imbrn** [comment]
What do you think about this rule @sebastianbarfurth ?

**Comment by sebastianbarfurth** [comment]
Really liking the idea @imbrn ! I think this can be very useful.

**Comment by imbrn** [comment]
Why do you think that, @RodolfoSilva? This rule is not a big one, and this can make the library core more useful, I think.

**Comment by RodolfoSilva** [comment]
I'm thinking of more features to put inside the schema. For example:

* The schema can return a plain object indicating which field is invalid.
* Set the error message for each field in the schema.
...

Or you can set this feature to be imported separately, like `import 'v8n/schema';`.

**Comment by sebastianbarfurth** [comment]
I feel like the footprint is sufficiently small to allow integration into the core. A modularization strategy needs to be made up in future anyways, for now I think the core is the best place for this.

I like the custom error idea though.

**Comment by imbrn** [comment]
I got you, @RodolfoSilva. But this is not how this library is supposed to work.

We should keep the Single Responsibility Principle in mind. We shouldn't make messages part of the validation process. This is an application layer detail.

And the **schema** is just a rule, we should think about it as just a verification to be done in our validation to ensure it conforms as we expect. Then we can use the validatoin response to make decisions about our logic. This abstraction makes this library useful for more use cases, I think.
