### ISSUE TITLE
Improve the look and feel of docs

### ISSUE THREAD

**Issue by sebastianbarfurth** [imbrn/v8n#56]
The README is very long and daunting. I would consider using either something like [GitBook](https://github.com/GitbookIO/gitbook) or [VuePress](https://github.com/vuejs/vuepress) for external docs or at least moving the entire API to a separate ``API.md`` file. The docs could generally be a bit nicer to look at, so I would also possibly consider switching `documentation.js` for manual creation which would also make the code nicer, since JSDoc is extremely space-consuming.

**Comment by imbrn** [comment]
I agree with you. We really need to break the README file, it's getting bigger every day. I also agree with the idea of switching from `JSDoc` style to a manual approach.

**Comment by sebastianbarfurth** [comment]
I may be able to tackle that tomorrow or even later today unless you wanna get started right away.

**Comment by imbrn** [comment]
You can tackle it in your time. I don't think it's something urgent anyway.

**Comment by iangilman** [comment]
I'd like to put a vote in for organizing the rules documentation somehow… At the moment the order seems kind of arbitrary. It should either be alphabetic or grouped in some logical fashion (and if it's grouped, it should be clear what the criteria is).

Thanks for an awesome library, by the way!

**Comment by imbrn** [comment]
We should go with VuePress for this. It looks much nicer to me.

**Comment by imbrn** [comment]
@sebastianbarfurth I'm going to clean the codebase by removing the JSDoc comments. Do you think you can finish the documentation before we go with the v1.1.0?
