### ISSUE TITLE
Npm package doesn't include .schema

### ISSUE THREAD

**Issue by djesmond** [imbrn/v8n#62]
I was trying to use the `.schema` function described in the docs and ran into an error. 
After digging around i found that it it hasn't been published on npm yet. 
I realise that it was included very recently and so it's understandable.
Just wanted to give you guys a heads up!

My work around was simply to copy the implementation from the src and inject it as a custom rule.

**Comment by sebastianbarfurth** [comment]
Yeah, you're right. ``schema`` was added recently and will be part of 1.1.0. Due to the current setup of branches and docs the docs may be ahead of the current npm release. This will be fixed soon.

Your approach seems like a fair workaround for the moment.
