### ISSUE TITLE
error TypeError: v8n(...).schema is not a function

### ISSUE THREAD

**Issue by alexisab** [imbrn/v8n#65]
Hi !

I try to use the `schema` rule to validate objects. Here is my code : 

```
const v8n = require('v8n')

const validate = (obj, specs) => {
    try {
        const validation = v8n().schema(specs)

        validation.check(obj)

        return obj
    } catch (error) {
        console.log('error', error)
    }
}

const { accessId, password } = validate(myObject, {
  accessId: v8n().string(),
  password: v8n().string().minLength(8).maxLength(40)
})
```

When I execute this code I got this error : 
```
error TypeError: v8n(...).schema is not a function
```

I don't understand what's wrong ?

v8n: 1.0.2
node: 9.10.0

**Comment by imbrn** [comment]
Actually the rule `schema` is not part of our last release (1.0.2), but it's on development yet and It'll be part of the next release (1.2.0) we're planning to ship in a few days. Sorry for the documentation messy, but we're going to fix this with a dedicated docs page for the latest release. But for now if you want to see the latest version documentation, look at this link https://github.com/imbrn/v8n/tree/v1.0.2

**Comment by alexisab** [comment]
Ok thanks for the explanation. You should use the `master` branch as the latest version and create a `dev` branch to develop new features. I think it would avoid that kind of mistake 😃 .

**Comment by imbrn** [comment]
@alexisab Thank you for your contribution. As I said, we're going to move all the documentation stuff from README to a dedicated page in a few days.
