### ISSUE TITLE
Add rule "optional"

### ISSUE THREAD

**Issue by imbrn** [imbrn/v8n#94]
This is a simple rule but that can add a lot of flexibility to the library.

It should be a composite rule. It must get a validation as input and should pass when this validation passes or when the validated value is not defined (`null` or `undefined`).

```javascript
const validation = v8n()
  .optional(
    v8n().number().positive()
  );

validation.test(-1); // false
validation.test(1); // true
validation.test(null); // true
```

Note: its implementation should use `check` instead of `test` to provide better error handling.

**Comment by sebastianbarfurth** [comment]
Lots of validation nesting recently. Could there a nicer way to implement something like this? Maybe another argument on the test functions?

**Comment by imbrn** [comment]
This rule is very straightforward and looks very clean to me. Also, we can benefit from the already implemented error handling system which works very well with `rules`.

I don't think we need to change our API now just to support this kind of feature. This would be a challenge to make it work for all kind of validations. It would be also hard to make it work with the already in use error handling system.

**Comment by sebastianbarfurth** [comment]
Is this no basically the same as:

```js
v8n()
  .passesAnyOf(
    v8n().null(),
    v8n().number().positive()
  )
  .test(...);
```

**Comment by imbrn** [comment]
almost that,

actually, we also need to check for `undefined`:

```javascript
v8n()
  .passesAnyOf(
    v8n().null(),
    v8n().undefined(),
    v8n().number().positive()
  )
```

The `optional` rule would be a kind of a shorthand for that.

**Comment by sebastianbarfurth** [comment]
I guess it's a fine shortcut then 👍

**Comment by imbrn** [comment]
Can you make a PR for this? 😁
