### ISSUE TITLE
Create a process for pull requests

### ISSUE THREAD

**Issue by sebastianbarfurth** [imbrn/v8n#96]
There should be a defined process for new features. I believe a good starting point would be a pull request template containing a checklist for all important tasks when changing something.

The main points should be:

```md
- [ ] Tests are passing
- [ ] The code is properly formatted with Prettier
- [ ] The code is commented or easily understandable
- [ ] Changes are documented
- [ ] Changes are added to the `Unreleased` section within the changelog
```

Can you think of additional points or change any? What else should be in the template?

**Comment by imbrn** [comment]
I agree! We certainly need a PR template. Those main points look correct, but I don't know if we actually need to point tasks like "tests" and "formatting". These kinds of tasks we need to enforce by the build process anyway.

**Comment by sebastianbarfurth** [comment]
Fair enough if they're pre-commit hooked. They pre-commit hooks don't apply to non source files, so we gotta keep that in mind. Make sure there is consistent formatting between docs and code and a consistent style within docs.

**Comment by imbrn** [comment]
Actually, they're not pre-commit hooked at this moment, and we should we fix that.

**Comment by sebastianbarfurth** [comment]
Husky is on pre-commit right? At least on my end.

**Comment by imbrn** [comment]
Yeah, but it's configured to run "prettier" just for source code files. I'm going to fix that to also run for markdown files.

**Comment by sebastianbarfurth** [comment]
Seems about right. Might as well add the Pull request template while you're at it.

**Comment by imbrn** [comment]
Ok, I'll add it too.
